---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: my-cluster-mp-0
  namespace: default
spec:
  clusterName: my-cluster
  replicas: 2
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: my-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPManagedMachinePool
        name: my-cluster-mp-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedMachinePool
metadata:
  name: my-cluster-mp-0
  namespace: default
spec: {}
