---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedCluster
metadata:
  name: my-cluster
  namespace: default
spec:
  network:
    name: default
  project: containerly-377101
  region: us-east1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPManagedControlPlane
metadata:
  name: my-cluster-control-plane
  namespace: default
spec:
  location: us-east1
  project: containerly-377101
